services:
  postgres_db:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    networks:
      - eb_network

  redis_cache:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - eb_network

  eb_presentation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      
      
    depends_on:
      - postgres_db
      - redis_cache
    ports:
      - "5000:5000"
    volumes:
       - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
       - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - eb_network


volumes:
  redis_data:
  postgres_db_volume:
   
networks:
  eb_network:
    driver: bridge